global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
global using Dapper;
global using Flurl.Http;
global using Microsoft.Data.SqlClient;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Data;
global using System.Text.Json.Serialization;